### ISSUE TITLE
Use from font CDN?

### ISSUE THREAD

**Issue by GekkotaDev** [rektdeckard/departure-mono#9]
Not a deal breaker but it would be nice to have Departure Mono on Google Fonts and/or Bunny Fonts.

More so interested in installing Departure Mono with [Fontsource](https://github.com/fontsource/font-files/issues/86#issue-2554951564), noted [here](https://github.com/fontsource/font-files/issues/74) maintainer/s may want it on Google Fonts first.

Being able to use it on Figma without the font installer and on Google Docs is also nice to have.

**Comment by harrisrobin** [comment]
+1 for this, would love to have this in google fonts.

**Comment by rektdeckard** [comment]
We're working on submitting to Google Fonts 👍

**Comment by sean-zlai** [comment]
@rektdeckard any update on submitting to Google Fonts?  I personally would love it available via Fontsource.

**Comment by kimslawson** [comment]
another +1 for google fonts inclusion. @rektdeckard do you know the status of this?

**Comment by bensterne** [comment]
+1 to wanting this. In the meantime, I forked the repo and set up GitHub Pages so it's accessible as a webfont if anyone needs it: https://bensterne.github.io/departure-mono-cdn/public/assets/DepartureMono-Regular.woff2
Note: unofficial, use at your own risk.

**Comment by rcastellotti** [comment]
While waiting for google fonts, you can use [`cdn.jsdeliver.net`](https://www.jsdelivr.com/?docs=gh), with something like:

```css
@font-face {
  font-family: "Departure Mono";
  src: url("https://cdn.jsdelivr.net/gh/rektdeckard/departure-mono@main/public/assets/DepartureMono-Regular.woff2") format("woff2");
}
```

P.S.: incredible font! kudos @drupol @rektdeckard <3
